CREATE TABLE reuseable_cron (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  description     VARCHAR(200),
  expression      VARCHAR(200)  NOT NULL,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_rc_expression UNIQUE (expression)
);

 CREATE TABLE user_account (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  username VARCHAR(200)  NOT NULL,
  mobile VARCHAR(64)  NOT NULL,
  email VARCHAR(200)  NOT NULL,
  password VARCHAR(200)  NOT NULL,
  account_non_expired BOOLEAN NOT NULL,
  account_non_locked BOOLEAN NOT NULL,
  credentials_non_expired BOOLEAN NOT NULL,
  enabled BOOLEAN NOT NULL,
  description VARCHAR(200),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_ua_email UNIQUE (email),
  CONSTRAINT unique_ua_name UNIQUE (username),
  CONSTRAINT unique_ua_mobile UNIQUE (mobile)
);

 CREATE TABLE user_role (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  role VARCHAR(200)  NOT NULL,
  description VARCHAR(200),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_ur_role UNIQUE (role),
);

CREATE TABLE user_and_role (
  user_id INT  NOT NULL,
  role_id INT  NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES user_account (id),
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id)  REFERENCES user_role (id)
);


CREATE TABLE user_grp
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  ename VARCHAR(256),
  msgkey VARCHAR(256),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_usergrp_ename UNIQUE (ename)
);

CREATE TABLE usergrp_and_user (
  user_id INT  NOT NULL,
  grp_id    INT  NOT NULL,
  PRIMARY KEY (user_id, grp_id),
  CONSTRAINT fk_ugu_user     FOREIGN KEY (user_id)  REFERENCES user_account (id),
  CONSTRAINT fk_ugu_grp       FOREIGN KEY (grp_id)    REFERENCES user_grp   (id)
);

CREATE TABLE big_ob
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  name VARChAR(256) NOT NULL,
  description VARCHAR(256),
  content BLOB,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_big_ob_name UNIQUE (name)
);

CREATE TABLE job_log
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  job_class VARCHAR(128),
  ctx VARCHAR(256),
  exp BLOB,
  created_at TIMESTAMP(2)
);

CREATE TABLE key_value
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  item_key VARCHAR(256) NOT NULL,
  item_value VARCHAR(256) NOT NULL,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_key_value_key UNIQUE (item_key)
);

CREATE INDEX job_log_created_at_idx ON job_log(created_at);